apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: irc-fava-casa
  namespace: ergo
spec:
  secretName: irc-fava-casa-tls
  duration: 2160h
  renewBefore: 360h
  dnsNames:
  - "irc.fava.casa"
  issuerRef:
    name: letsencrypt
    kind: Issuer
