apiVersion: v1
kind: ConfigMap
metadata:
  name: ergo-cm
  namespace: ergo
  labels:
    app: ergo
data:
  ircd.yaml: |
    network:
    name: favacasa
    server:
    name: irc.fava.casa
    listeners:
        "127.0.0.1:6667":
        "[::1]:6667":
        ":6697":
        tls:
            cert: fullchain.pem
            key: privkey.pem
        proxy: false
        min-tls-version: 1.2
    unix-bind-mode: 0777
    tor-listeners:
        require-sasl: false
        vhost: "tor-network.onion"
        max-connections: 64
        throttle-duration: 10m
        max-connections-per-duration: 64
    sts:
        enabled: false
        duration: 1mo2d5m
        port: 6697
        preload: false
    websockets:
        allowed-origins:
    casemapping: "ascii"
    enforce-utf8: true
    lookup-hostnames: false
    forward-confirm-hostnames: true
    check-ident: false
    coerce-ident: "~u"
    motd: ergo.motd
    motd-formatting: true
    relaymsg:
        enabled: true
        separators: "/"
        available-to-chanops: true
    proxy-allowed-from:
        - localhost
    max-sendq: 96k
    compatibility:
        force-trailing: true
        send-unprefixed-sasl: true
        allow-truncation: false
    ip-limits:
        count: true
        max-concurrent-connections: 16
        throttle: true
        window: 10m
        max-connections-per-window: 32
        cidr-len-ipv4: 32
        cidr-len-ipv6: 64
        exempted:
        - "localhost"
    ip-check-script:
        enabled: false
        command: "/usr/local/bin/check-ip-ban"
        args: []
        timeout: 9s
        kill-timeout: 1s
        max-concurrency: 64
        exempt-sasl: false
    ip-cloaking:
        enabled: true
        enabled-for-always-on: true
        netname: "irc"
        cidr-len-ipv4: 32
        cidr-len-ipv6: 64
        num-bits: 64
    secure-nets:
    suppress-lusers: false
    additional-isupport:
    accounts:
    authentication-enabled: true
    registration:
        enabled: true
        allow-before-connect: true
        throttling:
        enabled: true
        duration: 10m
        max-attempts: 30
        bcrypt-cost: 4
        verify-timeout: "32h"
        email-verification:
        enabled: false
        sender: "admin@my.network"
        require-tls: true
        helo-domain: "my.network"
        address-blacklist:
        address-blacklist-syntax: "glob"
        timeout: 60s
        password-reset:
            enabled: false
            cooldown: 1h
            timeout: 1d
    login-throttling:
        enabled: true
        duration: 1m
        max-attempts: 3
    skip-server-password: false
    login-via-pass-command: true
    advertise-scram: true
    require-sasl:
        enabled: false
        exempted:
        - "localhost"
    nick-reservation:
        enabled: false
        additional-nick-limit: 0
        method: strict
        allow-custom-enforcement: false
        guest-nickname-format: "Guest-*"
        force-guest-format: false
        force-nick-equals-account: true
        forbid-anonymous-nick-changes: false
    multiclient:
        enabled: true
        allowed-by-default: true
        always-on: "opt-in"
        auto-away: "opt-in"
    vhosts:
        enabled: true
        max-length: 64
        valid-regexp: '^[0-9A-Za-z.\-_/]+$'
    default-user-modes: +i
    auth-script:
        enabled: false
        command: "/usr/local/bin/authenticate-irc-user"
        args: []
        autocreate: true
        timeout: 9s
        kill-timeout: 1s
        max-concurrency: 64
    oauth2:
        enabled: false
        autocreate: true
        auth-script: false
        introspection-url: "https://example.com/api/oidc/introspection"
        introspection-timeout: 10s
        client-id: "ergo"
        client-secret: "4TA0I7mJ3fUUcW05KJiODg"
    jwt-auth:
        enabled: false
        autocreate: true
        tokens:
        - algorithm: "hmac"
            key: "nANiZ1De4v6WnltCHN2H7Q"
            account-claims: ["preferred_username"]
    channels:
    default-modes: +ntC
    max-channels-per-client: 100
    operator-only-creation: false
    registration:
        enabled: true
        operator-only: false
        max-channels-per-account: 15
    list-delay: 0s
    invite-expiration: 24h
    oper-classes:
    "chat-moderator":
        title: Chat Moderator
        capabilities:
        - "kill"
        - "ban"
        - "nofakelag"
        - "relaymsg"
        - "vhosts"
        - "sajoin"
        - "samode"
        - "snomasks"
        - "roleplay"
    "server-admin":
        title: Server Admin
        extends: "chat-moderator"
        capabilities:
        - "rehash"
        - "accreg"
        - "chanreg"
        - "history"
        - "defcon"
        - "massmessage"
    opers:
    admin:
        class: "server-admin"
        hidden: true
        whois-line: is the server administrator
    logging:
    - method: stderr
        type: "* -userinput -useroutput"
        level: info
    debug:
    recover-from-errors: true
    lock-file: "ircd.lock"
    datastore:
    path: ircd.db
    autoupgrade: true
    mysql:
        enabled: false
        host: "localhost"
        port: 3306
        user: "ergo"
        password: "hunter2"
        history-database: "ergo_history"
        timeout: 3s
        max-conns: 4
    languages:
    enabled: true
    default: en
    path: languages
    limits:
    nicklen: 16
    identlen: 16
    realnamelen: 32
    channellen: 16
    awaylen: 390
    kicklen: 390
    topiclen: 390
    monitor-entries: 100
    whowas-entries: 100
    chan-list-modes: 100
    registration-messages: 1024
    multiline:
        max-bytes: 4096
        max-lines: 100
    fakelag:
    enabled: true
    window: 1s
    burst-limit: 5
    messages-per-window: 2
    cooldown: 2s
    command-budgets:
        "CHATHISTORY": 16
        "MARKREAD": 16
        "MONITOR": 1
        "WHO": 4
        "WEBPUSH": 1
    roleplay:
    enabled: false
    require-oper: false
    require-chanops: false
    add-suffix: true
    history:
    enabled: false
    channel-length: 2048
    client-length: 256
    autoresize-window: 3d
    autoreplay-on-join: 0
    chathistory-maxmessages: 1000
    znc-maxmessages: 2048
    restrictions:
        expire-time: 1w
        query-cutoff: "none"
        grace-period: 1h
    persistent:
        enabled: false
        unregistered-channels: false
        registered-channels: "opt-out"
        direct-messages: "opt-out"
    retention:
        allow-individual-delete: false
        enable-account-indexing: false
    tagmsg-storage:
        default: false
        whitelist:
        - "+draft/react"
        - "+react"
    allow-environment-overrides: true
    webpush:
    enabled: false
    timeout: 10s
    delay: 0s
    max-subscriptions: 4
    expiration: 14d
    api:
    enabled: false
    listener: "127.0.0.1:8089"
    bearer-tokens:
        - "example"

  ergo.motd: |
    Welcome to the Fava Casa IRC Network!
     __                                     
    / _|                                    
    | |_ __ ___   ____ _  ___ __ _ ___  __ _ 
    |  _/ _` \ \ / / _` |/ __/ _` / __|/ _` |
    | || (_| |\ V / (_| | (_| (_| \__ \ (_| |
    |_| \__,_| \_/ \__,_|\___\__,_|___/\__,_|
                                                    
    Rules:                                                            
    - Be respectful to all users.                                    
    - No spamming, flooding, or advertising.                         
    - No harassment or hate speech.                         
    - Follow all network staff instructions.                         

    Useful Commands:                                                  
    - /join #channel  → Join a chat room.                            
    - /nick NewNick   → Change your nickname.                        

    Enjoy your stay!                                                 
