apiVersion: v1
kind: PersistentVolume
metadata:
  name: ergo-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: openebs-hostpath
