apiVersion: v1
kind: PersistentVolume
metadata:
  name: ergo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: openebs-hostpath
  hostPath:
    path: /mnt/data/ergo
