apiVersion: v1
kind: Service
metadata:
  name: ergo-service
  namespace: ergo
spec:
  type: NodePort
  selector:
    app: irc-server
  ports:
    - name: irc
      port: 6667
      targetPort: 6667
      nodePort: 30667
    - name: irc-tls
      port: 6697
      targetPort: 6697
      nodePort: 30697
