apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ergo
  namespace: ergo
  labels:
    app: ergo
spec:
  serviceName: "ergo"
  replicas: 1
  selector:
    matchLabels:
      app: ergo
  template:
    metadata:
      labels:
        app: ergo
    spec:
      containers:
      - name: ergo
        image: ghcr.io/ergochat/ergo:v2.15.0
        imagePullPolicy: Always
        ports:
        - containerPort: 6667
          name: irc
        - containerPort: 6697
          name: irc-ssl
        env:
        - name: ERGO__OPERS__ADMIN__PASSWORD
          valueFrom:
            secretKeyRef:
              name: ergo-secrets
              key: admin-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - name: ergo-data
          mountPath: /ircd
        - name: ergo-config-volume
          mountPath: /ircd/ircd.yaml
          subPath: ircd.yaml
        - name: ergo-config-volume
          mountPath: /ircd/ergo.motd
          subPath: ergo.motd
        - name: ergo-tls
          mountPath: /ircd/fullchain.key
          subPath: tls.crt
        - name: ergo-tls
          mountPath: /ircd/private.key
          subPath: tls.key          
      volumes:
      - name: ergo-config-volume
        configMap:
          name: ergo-cm
      - name: ergo-tls
        secret:
          secretName: irc-fava-casa-tls         
  volumeClaimTemplates:
  - metadata:
      name: ergo-data
    spec:
      storageClassName: openebs-hostpath
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
